# Generated by Django 4.2 on 2025-05-27 03:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('weight_loss', 'ลดน้ำหนัก'), ('muscle_building', 'สร้างกล้ามเนื้อ'), ('cardio', 'คาร์ดิโอ'), ('general', 'ทั่วไป')], default='general', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='content/')),
                ('is_published', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailyMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField()),
            ],
            options={
                'ordering': ['day_number'],
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('muscle_group', models.CharField(choices=[('chest', 'หน้าอก'), ('back', 'หลัง'), ('shoulders', 'ไหล่'), ('arms', 'แขน'), ('legs', 'ขา'), ('core', 'แกนกลาง'), ('full_body', 'ทั้งร่างกาย')], max_length=20)),
                ('difficulty', models.CharField(choices=[('beginner', 'มือใหม่'), ('intermediate', 'ปานกลาง'), ('advanced', 'ขั้นสูง')], max_length=20)),
                ('instructions', models.TextField()),
                ('video_url', models.URLField(blank=True)),
                ('equipment_required', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ExercisePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(choices=[('weight_loss', 'ลดน้ำหนัก'), ('fat_loss', 'ลดไขมัน'), ('muscle_gain', 'สร้างกล้ามเนื้อ'), ('endurance', 'เพิ่มความอดทน'), ('general_fitness', 'สุขภาพทั่วไป')], max_length=20)),
                ('level', models.CharField(choices=[('beginner', 'มือใหม่'), ('intermediate', 'ปานกลาง'), ('advanced', 'ขั้นสูง')], max_length=20)),
                ('days_per_week', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], default=3)),
                ('preferred_time', models.CharField(choices=[('morning', 'เช้า'), ('afternoon', 'บ่าย'), ('evening', 'เย็น')], default='evening', max_length=20)),
                ('training_focus', models.CharField(choices=[('full_body', 'ทั้งร่างกาย'), ('upper_lower', 'ส่วนบน/ส่วนล่าง'), ('push_pull_legs', 'ดัน/ดึง/ขา')], default='full_body', max_length=20)),
                ('available_equipment', models.BooleanField(default=False, help_text='มีอุปกรณ์ออกกำลังกายที่บ้านหรือไม่')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ForumTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('last_activity', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'รอดำเนินการ'), ('paid', 'ชำระแล้ว'), ('shipped', 'จัดส่งแล้ว'), ('delivered', 'ได้รับสินค้าแล้ว'), ('cancelled', 'ยกเลิก')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('instructions', models.TextField()),
                ('prep_time', models.IntegerField(help_text='เวลาเตรียม (นาที)')),
                ('cook_time', models.IntegerField(help_text='เวลาปรุง (นาที)')),
                ('servings', models.IntegerField(default=1)),
                ('calories_per_serving', models.IntegerField()),
                ('protein', models.FloatField(help_text='โปรตีน (กรัม)')),
                ('carbs', models.FloatField(help_text='คาร์โบไฮเดรต (กรัม)')),
                ('fat', models.FloatField(help_text='ไขมัน (กรัม)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='recipes/')),
                ('meal_type', models.CharField(choices=[('breakfast', 'อาหารเช้า'), ('lunch', 'อาหารกลางวัน'), ('dinner', 'อาหารเย็น'), ('snack', 'อาหารว่าง')], max_length=20)),
                ('diet_type', models.CharField(choices=[('any', 'ทั่วไป'), ('vegetarian', 'มังสวิรัติ'), ('vegan', 'วีแกน'), ('low_carb', 'คาร์บต่ำ'), ('high_protein', 'โปรตีนสูง')], default='any', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('duration', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='monthly', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('video_url', models.URLField()),
                ('thumbnail', models.ImageField(upload_to='video_thumbnails/')),
                ('category', models.CharField(choices=[('beginner', 'สำหรับผู้เริ่มต้น'), ('intermediate', 'ระดับกลาง'), ('advanced', 'ระดับสูง'), ('equipment', 'การใช้อุปกรณ์')], max_length=20)),
                ('duration', models.IntegerField(help_text='ความยาวในวินาที')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('published', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField()),
                ('focus', models.CharField(choices=[('rest', 'พักผ่อน'), ('cardio', 'คาร์ดิโอ'), ('strength', 'เวทเทรนนิ่ง'), ('flexibility', 'ความยืดหยุ่น'), ('hiit', 'HIIT'), ('upper_body', 'ส่วนบน'), ('lower_body', 'ส่วนล่าง'), ('full_body', 'ทั้งร่างกาย')], max_length=20)),
                ('exercise_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_days', to='myapp.exerciseplan')),
            ],
            options={
                'ordering': ['day_number'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.IntegerField(default=3)),
                ('reps', models.CharField(default='10-12', max_length=20)),
                ('rest_time', models.IntegerField(default=60, help_text='เวลาพักระหว่างเซ็ต (วินาที)')),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.exercise')),
                ('workout_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='myapp.workoutday')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'ชาย'), ('female', 'หญิง'), ('other', 'อื่นๆ')], max_length=10, null=True)),
                ('height', models.FloatField(blank=True, help_text='ความสูง (ซม.)', null=True)),
                ('weight', models.FloatField(blank=True, help_text='น้ำหนัก (กก.)', null=True)),
                ('activity_level', models.IntegerField(choices=[(1, 'ไม่ค่อยได้ออกกำลังกาย'), (2, 'ออกกำลังกายเบาๆ 1-3 วัน/สัปดาห์'), (3, 'ออกกำลังกายปานกลาง 3-5 วัน/สัปดาห์'), (4, 'ออกกำลังกายหนัก 6-7 วัน/สัปดาห์'), (5, 'ออกกำลังกายหนักมาก (นักกีฬา)')], default=1)),
                ('medical_conditions', models.TextField(blank=True, help_text='โรคประจำตัวหรือข้อจำกัดทางการแพทย์')),
                ('has_completed_profile', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=10)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.subscriptionplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('exercise_minutes', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='myapp.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='NutritionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(choices=[('weight_loss', 'ลดน้ำหนัก'), ('muscle_gain', 'เพิ่มกล้ามเนื้อ'), ('maintenance', 'รักษาสภาพ'), ('general_health', 'สุขภาพทั่วไป')], default='general_health', max_length=20)),
                ('dietary_restriction', models.TextField(blank=True, help_text='ข้อจำกัดด้านอาหาร เช่น แพ้อาหาร')),
                ('calorie_target', models.IntegerField(default=2000)),
                ('protein_ratio', models.IntegerField(default=30, help_text='เปอร์เซ็นต์ของโปรตีน')),
                ('carb_ratio', models.IntegerField(default=40, help_text='เปอร์เซ็นต์ของคาร์โบไฮเดรต')),
                ('fat_ratio', models.IntegerField(default=30, help_text='เปอร์เซ็นต์ของไขมัน')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(choices=[('weight_loss', 'ลดน้ำหนัก'), ('muscle_gain', 'สร้างกล้ามเนื้อ'), ('maintenance', 'รักษาสภาพ'), ('general_health', 'สุขภาพทั่วไป')], max_length=20)),
                ('daily_calories', models.IntegerField(default=2000)),
                ('protein_ratio', models.IntegerField(default=30, help_text='เปอร์เซ็นต์ของโปรตีน')),
                ('carb_ratio', models.IntegerField(default=40, help_text='เปอร์เซ็นต์ของคาร์โบไฮเดรต')),
                ('fat_ratio', models.IntegerField(default=30, help_text='เปอร์เซ็นต์ของไขมัน')),
                ('meals_per_day', models.IntegerField(choices=[(2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')], default=3)),
                ('dietary_restrictions', models.TextField(blank=True, help_text='ข้อจำกัดด้านอาหาร เช่น มังสวิรัติ, แพ้อาหาร')),
                ('allergies', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MealItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_time', models.CharField(choices=[('breakfast', 'อาหารเช้า'), ('lunch', 'อาหารกลางวัน'), ('dinner', 'อาหารเย็น'), ('snack', 'อาหารว่าง')], max_length=20)),
                ('daily_meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_items', to='myapp.dailymeal')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=50)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='myapp.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='ForumThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='myapp.forumtopic')),
            ],
        ),
        migrations.CreateModel(
            name='ForumReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='myapp.forumthread')),
            ],
        ),
        migrations.AddField(
            model_name='dailymeal',
            name='meal_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_meals', to='myapp.mealplan'),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles/')),
                ('category', models.CharField(choices=[('exercise', 'การออกกำลังกาย'), ('nutrition', 'โภชนาการ'), ('wellness', 'สุขภาพองค์รวม')], max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('published', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'product')},
            },
        ),
    ]
